services:
  hproxy:
    image: lexsos/hproxy:amd64
    restart: unless-stopped
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:8081:8081"
    volumes:
      - ./var/config.json:/config.json
    environment:
      APP_LOG_FORMAT: text
